server:
  port: 8084

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiService

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: activity-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            use:
              type:
                headers: false
            value:
              default:
                type: com.fitness.aiService.models.Activity
            trusted:
              packages: "*"

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.8-flash
            temperature: 0.5

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent
    key: ${GEMINI_API_KEY}

kafka:
  topic:
    name: activity-events